### ISSUE TITLE
Promise Compliance Tests

### ISSUE THREAD

**Issue by Akkuma** [chrisdavies/plite#4] opened 2016-05-04 20:36 UTC
https://github.com/promises-aplus/promises-tests

While trying to get a PR filled for adding plite to benchmarks for I had these comments about plite: https://github.com/briancavalier/creed/pull/7#issuecomment-216989634

I'm not sure how interested you are in being 100% compliant.

**Comment by chrisdavies** [comment] 2016-05-04 23:36
Yeah. I don't do setTimeout, but haven't run into any issues caused by it, other than that setTimeout slows things down significantly. My main goal was to allow chaining of then/catch, and await all functionality (the stuff I use on the front-end) more than anything else.

**Comment by nuKs** [comment] 2016-09-14 14:00
Agreed on the reason, however setTimeout is quite important for retro-compatibility. Could you remove the notice "Standards-compliant" from the doc please? For performance reasons, you still can add an optional argument to disable the setTimeout and be standard compliant.

It also seems like you do not handle exceptions like Promise/A+ do as well (they should be caught and reject the promise).

I may be mistaken though, didn't do expensive research.

**Comment by chrisdavies** [comment] 2016-09-14 21:25
Yeah. Good points all around. There was a case where I wasn't handling exceptions. Fixed now. Also, I removed the (false) standards compliant comment.

**Closed by chrisdavies** 2016-09-14 21:25 UTC
